version: "3.8"
services:
  mongodb:
    image: 'mongo'
    container_name: mongo-db
    volumes:
      - data:/data/db
    env_file:
      - .env
  backend:
    build: ./
    container_name: trades-node-app
    ports:
      - '8000:8000'
    env_file:
      - .env
    command: bash -c "npm run data:import && npm start"
    depends_on:
      - mongodb
volumes:
  data:
